<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| PUBLIC ROUTES — Anyone can visit these (logged in or not)
|--------------------------------------------------------------------------
*/

Route::get('/', function () {

    // Not logged in — show welcome page
    if (!Auth::check()) {
        return view('welcome');
    }

    // Logged in — redirect based on role
    $role = Auth::user()->role;

    if ($role === 'admin') {
        return redirect()->route('admin.dashboard');
    } elseif ($role === 'staff') {
        return redirect()->route('staff.dashboard');
    } else {
        return redirect()->route('customer.dashboard');
    }

});

/*
|--------------------------------------------------------------------------
| CUSTOMER ROUTES — Logged in users (any role can access these)
|--------------------------------------------------------------------------
*/

Route::middleware(['auth'])->group(function () {

    // Customer dashboard
    Route::get('/dashboard', function () {
        return view('customer.dashboard');
    })->name('customer.dashboard');

    // Profile routes — required by Breeze navigation
    Route::get('/profile', function () {
        return view('profile.edit');
    })->name('profile.edit');

});

/*
|--------------------------------------------------------------------------
| ADMIN ROUTES — Must be logged in AND have role = admin
|--------------------------------------------------------------------------
*/

Route::prefix('admin')
    ->middleware(['auth', 'admin'])
    ->name('admin.')
    ->group(function () {

        // Admin dashboard
        Route::get('/', function () {
            return view('admin.dashboard');
        })->name('dashboard');

        // Restaurant Tables CRUD
        Route::resource('tables', \App\Http\Controllers\Admin\RestaurantTableController::class);

        // Menu Categories CRUD
        Route::resource('categories', \App\Http\Controllers\Admin\MenuCategoryController::class);

        // Menu Items CRUD
        Route::resource('menu-items', \App\Http\Controllers\Admin\MenuItemController::class);

    });

/*
|--------------------------------------------------------------------------
| STAFF ROUTES — Must be logged in AND have role = staff
|--------------------------------------------------------------------------
*/

Route::prefix('staff')
    ->middleware(['auth', 'staff'])
    ->name('staff.')
    ->group(function () {

        // Staff dashboard
        Route::get('/', function () {
            return view('staff.dashboard');
        })->name('dashboard');

    });

/*
|--------------------------------------------------------------------------
| AUTH ROUTES — Login, Register, Logout (generated by Breeze)
|--------------------------------------------------------------------------
*/

require __DIR__.'/auth.php';